test: add a check for TransferSettings fields
Catches bug introduced in 483a11a40122d4bd7eb03ff548c737a322109c52
(SftpTransferManager: expose host key check choice): nullable Boolean is
not supported as a field type by core/ (fails at runtime with
java.lang.RuntimeException: Unknown type: class java.lang.Boolean).